name: Bump dependencies
on:
  schedule:
    # automatically bump dependencies at the first day every month
    - cron:  '0 12 1 * *'
  workflow_dispatch: {}
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: git config --global user.email "i@sem.ms"
      - run: git config --global user.name "Semesse"
      - run: npm i -g pnpm
      - run: pnpm up --latest
      - name: test if build & test pass
        run: pnpm build && pnpm tsc && pnpm test
      - run: 'git checkout -b "auto-bump-$GITHUB_RUN_ID"'
      - run: git add -A
      - run: 'git commit -m "chore: auto bump dependencies"'
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-bump-${{ env.GITHUB_RUN_ID }}
      - name: create pull request
        run: 'gh pr create -B master -H "auto-bump-$GITHUB_RUN_ID" --title "[CI] bump dependencies" --body "This PR passes all tests"'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
